.snyk
package.json

To continuously avoid known vulnerabilities in our dependencies,
this commit integrates Snyk into our TravisCI build.

Integrating Snyk into our dev workflow

---

README.md

In order to get automated code reviews for complexity and duplication
we are including Codeclimate badge.
This badge will link to reports about code health.

Including Codeclimate badge into README.md

---

.gitignore
fetcher/canVariablesFetcher.js
package.json
parser/equipmentParser.js
test/fetcher/canVariablesFetcher_spec.js
test/fixtures/facadeEquipmentFixture.json
test/fixtures/trackingPointFixture.json
test/models/equipment_spec.js
test/server_spec.js

We just added a request that will get the last position of each equipment and will merge this data inside the equipment request body.
We added [https://lodash.com/](lodash) as a dependency that will support to navigate between arrays and extract values.

Adding trackingDatum fetcher

---

app.js
config.js
fetcher/canVariablesFetcher.js

@waldemarnt and I did some refactors in code style and responsibilities

Some Refactoring

---

fetcher/canVariablesFetcher.js
test/fetcher/canVariablesFetcher_spec.js

Then new test case is to handle when the Telemetry API responde with empty trackingData
and trackingPoints

Adds test case Telemetry API search end point

---

app.js
config.js
schemas/equipmentSchema.js
validators/equipment.js

Given we want to provide narrative documentation around our endpoints,
including Swagger documentation is an important part of it.

Include Swagger documentation for Equipments

---

app.js
controllers/equipmentController.js
fetcher/canVariablesFetcher.js
fetcher/trackingPointFetcher.js
main.js
parser/equipmentParser.js
test/fetcher/canVariablesFetcher_spec.js
test/fetcher/equipmentFetcher_spec.js
test/fetcher/trackingPointFetcher_spec.js
test/helpers.js
test/models/equipment_spec.js
test/server_spec.js

This PR extracts the logic that was already present on the Can Variables Fetcher into an isolated Fetcher.

Extract Tracking point into a Fetcher

---

main.js

Hey folks, i just fixed the relative path of trackingPointFetcher

Fixes module import

---

config.js
test/fetcher/canVariablesFetcher_spec.js
test/helpers.js
test/server_spec.js

New can variables:
- MASTER_APPLY
- FUEL_LEVEL
- FUEL_RATE
- ENGINE_LOAD

Adds more default can variables

---

config.js

- MOISTURE_AVERAGE
- YIELD_AVERAGE
- CAPACITY_Average
- TEST_WEIGHT

Adds more can variables

---

config.js

- GRAIN_LOSS_Shaker
- GRAIN_LOSS_Rotor

Adds more defualt can variable

---

config.js

- CAPACITY
- MOISTURE
- BALE_WEIGHT_Total

Adds more default can variable

---

.eslintignore
fetcher/canVariablesFetcher.js
fetcher/trackingPointFetcher.js
package.json
parser/equipmentParser.js

This commit does:
- Creates a .eslintignore file that currently ignores
test/ (temporarily)
and node_modules/ directories
- Updates .eslintrc.js to include all the remaining JS files.
- Fixes lint problems

Updating Eslint definition

---

config.js
controllers/equipmentController.js
fetcher/canVariablesFetcher.js
fetcher/trackingPointFetcher.js

I just fixed some typos like **equipments** that need to be **equipment**

Fix equipment typos

---

schemas/equipmentSchema.js

This commit helps us giving proper names to most (not all) Swagger
definitions. There are still a few names that we were unable to change,
but they might not be relevant to our documentation.

Updating Swagger Model Names

---

.travis.yml

On each master commit, TravisCI is going to deploy to production and
sandbox environments.

Add multiple deployments

---

.travis.yml
contract_config.js
contract_helper.js
contract_http_client.js
contracts/telemetry_api/equipment/equipment/get_list.js
contracts/telemetry_api/equipment/equipment/get_one_by_id.js
package.json

We are adding contract tests to cover the communication
between equipment façade and telemetry API equipment resource

Adds contract tests to equipment

---

contract_helper.js
contracts/telemetry_api/equipment/trackingData/search_by_canVariables.js
contracts/telemetry_api/equipment/trackingData/search_last_trackingPoint.js
fetcher/canVariablesFetcher.js
fetcher/trackingPointFetcher.js
helper/trackingDataSearchHelper.js
parser/trackingDataSearchParser.js

This ensure that the search endpoint is delivering the expected
data.

Adding contract tests to search endpoint

---

docker-compose.yml
package.json
src/app.js
src/metrics/responseTimeExtractor.js
test/metrics/response_time_extractor_spec.js

Here @waldemarnt and I added Bunyan to write logs as JSON. 
In the first time we created a folder logs/metrics, but we figured out that we need a default log folder, so we added it too.
Besides of that, we also added a validation to verify if there is a authorization header.

Collect logs

---

monitoring/README.md
monitoring/docker-compose.yml
src/app.js

This commit:
* Document the monitoring architecture
* Document how we are using: Logstash, Elasticsearch, Kibana and Filebeat
* Document how to use it on a new project
Pairing with @lucaslago

Document our proof-of-concept

---

monitoring/docker-compose.yml

@carolinaborim and I just fixed a directory path.

Fix kibana config directory path
