README.md

This commit includes the following information on `README.md`:
- A small paragraph about the project;
- Execution instructions;
- Development commands.
[Resulting rendering is available here](https://github.com/agco-fuse/fuse-equipment-api/blob/1cd87a61a6480159fef92ca6de82286d4552dfed/README.md)

Adds more context about the project on README

---

controllers/equipmentController.js
test/server_spec.js

In case Telemetry API is not available the Equipment API keeps the
connection with the client open forever without sending any response.
The same behavior is reproducible in case we provide an invalid
Telemetry API URL,
In order to avoid that, we should close connections as soon as we find
this kind of problem.

Fix Equipment API integration issue

---

app.js
test/helpers.js
test/mocha.opts
test/server_spec.js

Currently on master there are some test cases that are producing some warnings:
With this changes, the warnings will be removed:
The major changes are:
- HTTP Mock client is being recreated between test scenarios to not get polluted between runs
- Removed mock verification when the exact arguments have been stubbed, in favor of verifying the behavior on the expected output.

Remove warnings on test

---

controllers/equipmentController.js
test/server_spec.js

This change includes pagination for equipments.
Now you can provide an `offset` and/or  `limit` parameters to paginate through your equipment list.
If the user don't provide any of these, we are assuming `offset = 0` and `limit = 100`.

Add pagination

---

app.js
test/server_spec.js

Apparently everybody that follows JSON API specification pluralize
theirs endpoints.

Pluralize Equipment endpoints

---

app.js
controllers/equipmentController.js
main.js
test/helpers.js
test/server_spec.js

We would like to remove the knowledge of dependent URLs from the Controller tests, as the component that makes the request is the one responsible to know this.
On this PR we are injecting the Can Variables Fetcher, so we can mock it during test and remove the HTTP requests from the controller test.
On a follow up PR, we are going to extract a Telemetry Fetcher, and do the same changes on the Controller test then.
Pairing with @andressa.

Refactoring tests

---

app.js
controllers/equipmentController.js
fetcher/equipmentFetcher.js
main.js
test/fetcher/equipmentFetcher_spec.js
test/helpers.js
test/server_spec.js

The idea of this PR is to remove the knowledge of HTTP from the controller.
The operations that fetch information from the external APIs are encapsulated into a Fetcher and orchestrated by the Controller.

Extract a Equipment Fetcher from controller

---

app.js

Given we don't know how our consumers are going to use the Equipment
API, we need to enable CORS.
We are doing it now because Equipment API is only a facade which reads
data from Telemetry API. We would not advise using this if Equipment API
starts inserting data.

Enabling CORS.

---

config.js
fetcher/canVariablesFetcher.js
fetcher/equipmentFetcher.js
fetcher/trackingPointFetcher.js
test/fetcher/canVariablesFetcher_spec.js
test/fetcher/equipmentFetcher_spec.js
test/fetcher/trackingPointFetcher_spec.js
test/models/equipment_spec.js
test/server_spec.js

Modern systems integrate with a lot of external dependencies. Most of
these dependencies are outside our control. While requesting content
from one of them, it could happen that it does not reply our
requests. Even worse would be if it decides to answer our requests at a
rate of one byte per second!
What could we do in this case? That is where Timeouts comes to rescue!

Adding timeouts to our HTTP requests

---

schemas/equipmentSchema.js

Given we do not know which CAN variable will be available for each
equipment, this commit just let consumers know that trackingData will be
a generic object.

Updating Swagger definition

---

.eslintrc.js
package.json

We are including the following lint rules:
- [no-commented-out-code](https://github.com/bahmutov/eslint-rules#no-commented-out-code)
Detects code in the single or multiline comments.
- [no-long-files](https://github.com/bahmutov/eslint-rules#no-long-files)
Detect source files with too many lines.
- [no-for-loops](https://github.com/bahmutov/eslint-rules#no-for-loops)
Warns or errors if you use for loops in your code.
- [potential-point-free](https://github.com/bahmutov/eslint-rules#potential-point-free)
Warns if a function just calls another function passing arguments and
can potentially become point-free.

Adding extra lint rules

---

schemas/equipmentSchema.js

Recently we included a lint rule to help us keeping our source files
shorter than 113 lines.
Unfortunately we merged a [pull request]
(https://github.com/agco-fuse/fuse-equipment-api/pull/43)
without re-running TravisCI and now our lint step is broken.
This commit updates `equipmentSchema` and fixes the lint problem.

Fix broken lint

---

app.js
controllers/equipmentController.js
test/controllers/equipment_controller_spec.js

Supporting `OPTIONS` HTTP method might help improving the API
discoverability by external agents.
This allows clients available operations for a given resource.
Previously, if you did an OPTIONS request to /equipment endpoint:
```
$ curl -X OPTIONS --user email@example.com:pass http://fuse-equipment-api.herokuapp.com/equipment          
```
You would receive a response such as:
```
< HTTP/1.1 404 Not Found
< Server: Cowboy
< Connection: keep-alive
< Content-Type: application/json; charset=utf-8
< Cache-Control: no-cache
< Content-Length: 84
< Date: Fri, 20 May 2016 14:47:53 GMT
< Via: 1.1 vegur
<
* Connection #0 to host fuse-equipment-api.herokuapp.com left intact
{"statusCode":404,"error":"Not Found","message":"CORS error: Missing Origin header"}%
```
Now, if you do an OPTIONS request to …

Add support for OPTIONS operation on /equipment endpoint

---

app.js
controllers/rootController.js
test/controllers/equipment_controller_spec.js
test/controllers/root_controller_spec.js

Right now root ('/') endpoint requests return a 404 HTTP status
code (Not Found).
That might not be the best behavior for an API in case we want to
improve its discoverability.
This commit includes a RootController whose responsibility is to list
all available resources under the API for external users.
Previously, if you did a GET request to / endpoint:
```
$ curl -X GET --user email@example.com:pass http://fuse-equipment-api.herokuapp.com/         
```
You would receive a response such as:
```
< HTTP/1.1 404 Not Found
< Server: Cowboy
< Connection: keep-alive
< Content-Type: application/json; charset=utf-8
< Cache-Control: no-cache
< Content-Length: 38< Date: Fri, 20 May 2016 16:21:52 GMT
< Via: 1.1 vegur
<
* Connection #0 to host fuse-equipment-api-sandbox.herokuapp.com left intact …
```

Add resource description on root ('/') endpoint

---

docker-compose.yml
elk/logstash/logstash.conf

We are about to start a proof-of-concept around monitoring.
We chose to use ELK (Elasticsearch - Logstash - Kibana) as our
monitoring stack.
Being able to run this stack locally will faster development.

Provision Monitoring Stack

---

jmeter/monitoring-load.jmx

We are about to start a proof-of-concept around monitoring and logging
and we need realistic data to make it happen.
This commit includes a JMeter script which simulates user access to our
Equipment Facade.

Including JMeter script to simulate user load

---

package.json
src/app.js

We thought we had fixed CORS issues a while ago. But it seems that we
haven't.
Today I noticed that the Facade does not support CORS while executing
our dealership demo example.
In order to finally fix this I included a simple hapi plugin which
includes all the necessary CORS headers.

Adds CORS support

---

package.json

The `engine` section should match the runtime we are using to develop
and test. Given we recently updated our codebase to use Node 6.2.2, we
should make Heroku use this version as well.
For further information, please checkout Heroku documentation: https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version

Specifies the Node version

---

docker-compose.yml
elk/logstash/logstash.conf
filebeat/filebeat.yml
src/app.js
src/metrics/responseTimeExtractor.js
test/metrics/response_time_extractor_spec.js

Based on discussions that we had today about the logging responsability, we changed the way that we are writing logs to be more generic.
The responsability to define in which index and type the data will be saved
was moved to logstash.
co-author: @waldemarnt

Changes logging logic

---

docker-compose.yml
monitoring/logstash/logstash.conf
monitoring/logstash/template.json

Folks @carolinaborim and I we just added a default template to elasticsearch.
This templates ensure that fields like ```email``` and ```uuid``` will be ```not_analyzed```.
We also fixed #68 docker-compose file paths in this commit https://github.com/agco-fuse/fuse-equipment-api/pull/69/commits/6c51b72eca777105aa8faaea3aeb309c3f79567d

Add elasticsearch template
